### ISSUE TITLE
Data required by fit_bert 

### ISSUE THREAD

**Issue by 904763189cy** [princetonvisualai/directional-bias-amp#3]
I encountered some issues while running  fit_bert.read_wiki2.py. 
I can't find the required files, such as english-adjectives.txt and wikitext-103.
Could you provide me with the necessary files？

Please forgive my interruption.

**Comment by Angelina-Wang** [comment]
The relevant files should be able to be found here:
- https://gist.github.com/hugsy/8910dc78d208e40de42deb29e62df913
- https://paperswithcode.com/dataset/wikitext-103
