### ISSUE TITLE
Data required by coco_captioning and coco_mask

### ISSUE THREAD

**Issue by ZhaotianWeng** [princetonvisualai/directional-bias-amp#4]
there is no data_split directory. like no val.data file? the file '/n/fs/visualai-scr/Data/Coco/2014data/bias_splits/val.data' is not included in this codebase.

**Comment by ZhaotianWeng** [comment]
Is there no bias_splits directory, like no val.data file? the file '/n/fs/visualai-scr/Data/Coco/2014data/bias_splits/val.data' is not included in this codebase? I met this problem when trying to run coco_captioning and coco_mask. 

Could you please tell me where to find this .data file? Sorry for my interruption.
Thank you so much!

**Comment by Angelina-Wang** [comment]
The data splits are located at this link (val.data is dev.data): https://github.com/uclanlp/reducingbias/tree/master/data/COCO

I have updated the README as well.
